export const comeonData = {
    title:{
        main:'出门装推荐',
        minor:[
            '登场率','胜率'
        ],
    },
    data:[
        {
            equire:[
                {
                    url:'https://game.gtimg.cn/images/lol/act/img/item/1055.png',
                    alt:'多兰之刃',
                },
                {
                    url:'https://game.gtimg.cn/images/lol/act/img/item/2003.png',
                    alt:'生命药水',
                }
            ],
            comeOnSpan:'53.48%',
            winSpan:'48.15%'
        },
        {
            equire:[
                {
                    url:'https://game.gtimg.cn/images/lol/act/img/item/1054.png',
                    alt:'多兰之盾',
                },
                {
                    url:'https://game.gtimg.cn/images/lol/act/img/item/2003.png',
                    alt:'生命药水',
                }
            ],
            comeOnSpan:'44.07%',
            winSpan:'47.16%'
        },
        {
            equire:[
                {
                    url:'https://game.gtimg.cn/images/lol/act/img/item/1036.png',
                    alt:'长剑',
                },
                {
                    url:'https://game.gtimg.cn/images/lol/act/img/item/2031.png',
                    alt:'复用型药水',
                }
            ],
            comeOnSpan:'44.07%',
            winSpan:'47.16%'
        }
    ]
}


export const mainData = {
    title:{
        main:'核心装推荐',
        minor:[
            '登场率','胜率'
        ],
    },
    data:[
        {
            equire:[
                {
                    url:'https://game.gtimg.cn/images/lol/act/img/item/6698.png',
                    alt:'亵渎九头蛇',
                },
                {
                    url:'https://game.gtimg.cn/images/lol/act/img/item/3814.png',
                    alt:'夜之锋刃',
                },
                {
                    url:'https://game.gtimg.cn/images/lol/act/img/item/6694.png',
                    alt:'赛瑞达尔的怨恨',
                }
            ],
            comeOnSpan:'6.75%',
            winSpan:'60.35%'
        },
        {
            equire:[
                {
                    url:'https://game.gtimg.cn/images/lol/act/img/item/6698.png',
                    alt:'亵渎九头蛇',
                },
                {
                    url:'https://game.gtimg.cn/images/lol/act/img/item/6610.png',
                    alt:'焚天',
                },
                {
                    url:'https://game.gtimg.cn/images/lol/act/img/item/3053.png',
                    alt:'斯特拉克的挑战护手',
                }
            ],
            comeOnSpan:'4.99%',
            winSpan:'58.2%'
        },
        {
            equire:[
                {
                    url:'https://game.gtimg.cn/images/lol/act/img/item/6698.png',
                    alt:'亵渎九头蛇',
                },
                {
                    url:'https://game.gtimg.cn/images/lol/act/img/item/6610.png',
                    alt:'焚天',
                },
                {
                    url:'https://game.gtimg.cn/images/lol/act/img/item/3161.png',
                    alt:'朔极之矛',
                }
            ],
            comeOnSpan:'4.19%',
            winSpan:'57.51%'
        }
    ]
}


export const shoeData = {
    title:{
        main:'鞋子推荐',
        minor:[
            '登场率','胜率'
        ],
    },
    data:[
        {
            equire:[
                {
                    url:'https://game.gtimg.cn/images/lol/act/img/item/3047.png',
                    alt:'铁板靴',
                },
            ],
            comeOnSpan:'69.75%',
            winSpan:'60.35%'
        },
        {
            equire:[
                {
                    url:'https://game.gtimg.cn/images/lol/act/img/item/3111.png',
                    alt:'水银之靴',
                }
            ],
            comeOnSpan:'4.99%',
            winSpan:'58.2%'
        },
        {
            equire:[
                {
                    url:'https://game.gtimg.cn/images/lol/act/img/item/3158.png',
                    alt:'明朗之靴',
                },
            ],
            comeOnSpan:'4.19%',
            winSpan:'57.51%'
        }
    ]
}

export const otherData = {
    title:{
        main:'其余装备',
        minor:[
            '登场率','胜率'
        ],
    },
    data:[
        {
            equire:[
                {
                    url:'https://game.gtimg.cn/images/lol/act/img/item/2504.png',
                    alt:'败魔',
                },
            ],
            comeOnSpan:'1.75%',
            winSpan:'50.35%'
        },
        {
            equire:[
                {
                    url:'https://game.gtimg.cn/images/lol/act/img/item/3026.png',
                    alt:'守护天使',
                }
            ],
            comeOnSpan:'4.99%',
            winSpan:'58.2%'
        },
        {
            equire:[
                {
                    url:'https://game.gtimg.cn/images/lol/act/img/item/3053.png',
                    alt:'斯特拉克的挑战护手',
                },
            ],
            comeOnSpan:'16.16%',
            winSpan:'56.94%'
        }
    ]
}